### PR TITLE
Avoid script snapshot creation if the --precompiled flag is set during builds

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by devoncarew** [comment]
(travis failure fixed here: https://github.com/flutter/tools/pull/116)

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
I'd be interested in hearing what all the moving pieces are here, but we can talk about that in person tomorrow.

**Comment by chinmaygarde** [comment]
@abarth Sounds good. This should be the only required change in the tools repo. The other changes are in engine and dart. Preparing PRs for them now.

**Pull request merged**
