### PR TITLE
Beginning implementation of IOSDevice. Implements list and install.

### PR DESCRIPTION
**Pull request by iansf**
Also update tests to be compatible with the presence of iOS and add tests for list and install.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by iansf** [comment]
Merging this to get unblocked.  @devoncarew and/or I will try to figure out why travis is failing only on the server.

**Comment by devoncarew** [comment]
Oddly, when I run the tests locally, I _do_ see output from pub get.

**Comment by devoncarew** [comment]
pub (and tests) run fine; travis is failing when it tries to archive up the pub-cache between builds.

https://api.travis-ci.org/jobs/83951133/log.txt?deansi=true

We should just remove that.

**Pull request merged**
