### PR TITLE
Don't hard-code the "release" flag when running with mojo_run on android

### PR DESCRIPTION
**Pull request by nlacasse**

### CODE REVIEW

**Comment by nlacasse** [comment]
cc @jamesr

**Comment by jamesr** [comment]
This needs to be configurable but I think the default should be release mode mojo as it's much faster.

**Comment by jamesr** [comment]
How about --mojo-debug / --mojo-release to control this?  This should also control the path in the run-on-linux case to switch between out/Debug/mojo_shell and out/Release/mojo_shell.

**Comment by nlacasse** [comment]
Isn't it already configurable, since we can pass "--release" to devtools/common/mojo_run in the "rest" arguments.

```
pub run sky_tools run_mojo --mojo-path $MOJO_DIR -- --release
```

Why do we call "mojo_shell" directly on Linux?  We could use "devtools/common/mojo_run" on Linux as well, and then we can pass "--release" in the same way.

**Comment by jamesr** [comment]
It is configurable but the default for mojo_run is debug, so this patch changes the default and it would be pretty difficult for this wrapper to figure out what you mean without parsing the rest of the arguments which gets messy.  That's why I'm suggesting having a flag to this script that configures things exactly.

This script doesn't use mojo_run on linux as that script is much slower without a corresponding benefit.

**Comment by nlacasse** [comment]
Ok that makes sense.  I'll work on the --mojo-release/--mojo-debug flags.  Thanks!

**Pull request closed without merging**
