### PR TITLE
Stop requiring customers to use a dev SDK

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
@devoncarew What bad things happens if we make this change?

/cc @Hixie

**Comment by devoncarew** [comment]
The new signing code is using a 1.13 class. It's tri ial - base64 maybe? - we could work around it easily enough.

**Comment by devoncarew** [comment]
To see which class, you can update this PR with a change in the travis.yml file to resume testing against dev and stable. Should call out the new class pretty quickly :)

**Comment by abarth** [comment]
I don't think we want to require customers to use the dev SDK.  Customers don't use the signing code yet, so maybe the SDK will rev by the time its ready.

**Comment by devoncarew** [comment]
(https://github.com/flutter/tools/pull/116)

**Comment by mpcomplete** [comment]
Yep, I think it's just base64 that the signing code needs. The dart/crypto package has a base64 de/encoder that I could use instead if we want to fix it.

**Comment by abarth** [comment]
@mpcomplete Ok, I'm going to land this patch to unblock developers that depend on us.  IMHO, we should switch to the other base64 encoder so we don't need to a dev version of the Dart SDK.  Thanks!

**Pull request merged**
