### PR TITLE
Get iOS devices working on Mac if you specify sky-src-path.

### PR DESCRIPTION
**Pull request by iansf**

### CODE REVIEW

**Comment by iansf** [comment]
This is failing because of dart analyzer warnings in the created test app, which (I'm fairly certain) has nothing to do with this.  Presumably an error in the pub get step where it is getting an out-of-date version of flutter (or the init command needs to be updated).

**Comment by jamesr** [comment]
The pub deps were busted briefly - is it possible to re-run travis?

**Comment by devoncarew** [comment]
re-running...

**Comment by jamesr** [comment]
Sorry, can't explain that failure

**Comment by devoncarew** [comment]
The failures look like real analysis issues w/ the template. I'll file an issue - don't think it should hold up this PR.

**Comment by iansf** [comment]
Thanks!  Merging.

**Comment by iansf** [comment]
(I guess technically that wasn't an lgtm...)

**Pull request merged**
