### PR TITLE
Refactor the build command so that it can be used internally

### PR DESCRIPTION
**Pull request by abarth**
Instead of calling through `pub` to invoke build, this patch refactors the
build command so that it can be called directly.

### CODE REVIEW

**Comment by abarth** [comment]
@devoncarew

**Comment by abarth** [comment]
@devoncarew I'm a bit stuck on getting the test to pass.  Any thoughts on how to setup the mock environment correctly?

**Comment by devoncarew** [comment]
I can repro locally; I'll take a look.

**Comment by abarth** [comment]
I wish there was something like http://www.dartdocs.org/documentation/quiver/0.21.4/index.html#quiver/quiver-testing-async.FakeAsync that mocked out the subprocesses...  I didn't see anything in quiver that does that.

**Comment by devoncarew** [comment]
@iansf has used the `mockito` package quite a bit; perhaps that could help out.

**Comment by iansf** [comment]
Hmm -- probably we should put the functions in process.dart into a class so that they are mockable with mockito.

**Comment by abarth** [comment]
Passes tests now.  PTAL

**Comment by devoncarew** [comment]
lgtm

**Pull request merged**
